### ISSUE TITLE
KaiOS Port

### ISSUE THREAD

**Issue by sjehuda** [nioc/xmpp-web#67] opened 2022-11-24 06:54 UTC
Port XMPP Web to GerdaOS/KaiOS (FirefoxOS).

There's no Jabber app currently.
https://store.bananahackers.net/
https://www.kaiostech.com/store/

**Comment by nioc** [comment] 2022-11-24 12:49
Duplicate of #6

**Closed** 2022-11-24 12:49 UTC
Labels: enhancement
