### ISSUE TITLE
Unble to connect Openfire through xmpp-web

### ISSUE THREAD

**Issue by etechkuldip** [nioc/xmpp-web#118] opened 2024-03-29 06:41 UTC
### Describe the bug

I have been trying to connect Openfire through xmpp-web. 

### Steps to reproduce

Openfire version : 4.7.5  => Disabled TLS V1.3 under port 5222

![image](https://github.com/nioc/xmpp-web/assets/78481129/0341b247-ac20-439b-bc30-22428b0e90c3)

Registration 

![image](https://github.com/nioc/xmpp-web/assets/78481129/60abb12a-ec37-4574-9998-e3ccfebc38ed)

Run App through from Vue.js => "preview": "vite build && vite preview --port 8080", 

![image](https://github.com/nioc/xmpp-web/assets/78481129/fcdc36f1-206b-425a-99ba-eaae37f40f90)

### Expected behavior

At least, I want to see the errors from console, its only showing **Error during login**. 

### local.js configuration

```js
// eslint-disable-next-line no-unused-vars, no-var
var config = {
  name: "XMPP web",
  transports: {
    websocket: "xmpp://kuldip-pc:5222", //'wss://chat.domain-web.ltd/xmpp-websocket',
  },
  hasGuestAccess: true,
  hasRegisteredAccess: true,
  anonymousHost: null,
  // anonymousHost: 'anon.domain-xmpp.ltd',
  isTransportsUserAllowed: false,
  hasHttpAutoDiscovery: false,
  resource: "Web XMPP",
  defaultDomain: "kuldip-pc",
  defaultMuc: null,
  // defaultMuc: 'conference.domain-xmpp.ltd',
  isStylingDisabled: false,
  hasSendingEnterKey: false,
  connectTimeout: 5000,
  pinnedMucs: [],
  logoUrl: "",
  guestDescription: "",
};
```

### XMPP-web version

0.10.0

### Installation

Build from source

### XMPP server(s)

Openfire

### Browser(s)

Chrome

### Device(s)

desktop

**Comment by nioc** [comment] 2024-03-30 17:26
Hello @etechkuldip

I don't know Openfire but with Prosody there is the [`cross_domain_websocket` parameter](https://github.com/nioc/xmpp-web/blob/master/docs/staging-environments/prosody-std/prosody.cfg.lua#L201) that need to be set with the web url (`http://localhost:8080/` in case of `npm run preview`).

can be identified by the 403 HTTP response (`GET ws://10.0.0.79:5280/xmpp-websocket`) in browser network tab:
```http
HTTP/1.1 403 Forbidden
Date: Sat, 30 Mar 2024 17:23:35 GMT
Content-Length: 401
Connection: Keep-Alive
Content-Type: text/html; charset=utf-8
```

As it work for me, I ask you to provide a [reproducing configuration](https://github.com/nioc/xmpp-web/blob/master/docs/staging-environments/REPRODUCING.MD).

**Comment by etechkuldip** [comment] 2024-03-31 07:04
@nioc  Thank you for your prompt reply. I comprehend your message, and I will replicate the process after altering my surroundings.

Here is the my new configuration,

`var config = {
  name: "XMPP web",
  transports: {
    websocket: "ws://kuldip-pc:5222/ws", 
  },
  hasGuestAccess: true,
  hasRegisteredAccess: true,
  anonymousHost: null,
  // anonymousHost: 'anon.domain-xmpp.ltd',
  isTransportsUserAllowed: false,
  hasHttpAutoDiscovery: false,
  resource: "Web-XMPP",
  defaultDomain: "kuldip-pc",
  defaultMuc: null,
  // defaultMuc: 'conference.domain-xmpp.ltd',
  isStylingDisabled: false,
  hasSendingEnterKey: false,
  connectTimeout: 5000,
  pinnedMucs: [],
  logoUrl: "",
  guestDescription: "",
};`


Now using **ws://kuldip-pc:5222/ws** , I am getting Server unreachable.

![image](https://github.com/nioc/xmpp-web/assets/78481129/e28cace7-b839-40e0-9518-e591965f416f)


I also increase timeout , but still the problem same.

Here is the openfire server ports list

![image](https://github.com/nioc/xmpp-web/assets/78481129/b6156952-bed9-4d32-81dd-880e1d152e0c)

I know ,you are not familiar but what should be a port and url to connect  ?
just help me with url or right connection url

**Comment by nioc** [comment] 2024-03-31 12:14
Probably something like this without TLS: `ws://your.openfire.host:7070/ws`

**Comment by etechkuldip** [comment] 2024-03-31 13:49
@nioc  Thanks sir, Its connected,but I am getting below error 

![image](https://github.com/nioc/xmpp-web/assets/78481129/0ed0ffcc-7d57-4dfe-a800-9cd1bf6fd029)

**Comment by nioc** [comment] 2024-03-31 14:08
The auth mechanism allowed by the [xmpp.js library](https://github.com/xmppjs/xmpp.js/blob/main/packages%2Fclient%2FREADME.md#authentication) is only PLAIN.
But it is not a problem using TLS (as the connection is secured).

Does your certificate is OK?
What the console/network tab says using the secure port (wss://…:7443)?
May be using `https` scheme instead of `wss`.
At least using a proxy (Apache or Nginx) may solve issue.

**Comment by nioc** [comment] 2024-03-31 14:20
And what about network tab for the WS request?

**Comment by etechkuldip** [comment] 2024-03-31 14:43
Nothing showing
![image](https://github.com/nioc/xmpp-web/assets/78481129/7e34be74-2765-4732-878b-5bdb9f451bf0)

**Comment by nioc** [comment] 2024-03-31 14:44
In the header tab?

**Comment by etechkuldip** [comment] 2024-03-31 14:47
![image](https://github.com/nioc/xmpp-web/assets/78481129/423953a0-c909-4110-82a0-920f580c503a)

**Comment by nioc** [comment] 2024-03-31 15:02
Strange behavior 😞 

I do not think it is a bug in the app or library (because it works without TLS in your setup and with TLS in mine).

So I thins about 2 leads:

- network: Are you sure the port 7443 is reachable (not closed by firewall for example)? Try a quick (with https scheme):
  ```
  curl https://kuldip-pc:7443/ws/
  ```
- Certificate: How do you set up certificate (self signed, from let's encrypt, ...)?

**Comment by etechkuldip** [comment] 2024-03-31 15:05
@nioc  Allow me some time, I will update you on what you suggest

**Comment by etechkuldip** [comment] 2024-03-31 15:17
![image](https://github.com/nioc/xmpp-web/assets/78481129/bb1e9011-f98c-4fb2-98d0-74fd332049cd)

**Comment by nioc** [comment] 2024-03-31 15:24
Looks like a certificate issue 😉

**Comment by etechkuldip** [comment] 2024-03-31 15:26
Ohh, thanks, Do you know how to fix it or reference, any link ? I am not familiar with it,

**Comment by nioc** [comment] 2024-03-31 15:36
For the cert creation: https://certbot.eff.org/
For use in OpenFire (just Googled 😆): https://meetrix.io/blog/xmpp/openfire_ssl.html

I close the issue but feel free to continue discussion.

**Closed by nioc** 2024-03-31 15:36 UTC
Labels: question, need repro

**Comment by guusdk** [comment] 2024-05-27 10:19
Openfire now has a plugin that lets you add XMPP Web automatically. You could use that, or use it for inspiration on how to configure a stand-alone instance of XMPP web.

More details on Openfire's plugin: https://discourse.igniterealtime.org/t/new-openfire-plugin-xmpp-web/
